title:
  "Naked Alarm Clock"
  
description:
  "nakedalarmclock.github.io"

github:
  "nakedalarmclock"

theme:
  jekyll-theme-cayman

permalink:
  pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
